CREATE DATABASE CSE_6B_411
USE CSE_6B_411
CREATE TABLE SALES_DATA
(
REGION VARCHAR(50),
PRODUCT VARCHAR(50),
SALES_AMOUNT INT,
YEAR INT
)
INSERT INTO SALES_DATA VALUES
('NORTH AMERICA','WATCH',1500,2023),
('EUROPE','MOBILE',1200,2023),
('ASIA','WATCH',1800,2023),
('NORTH AMERICA','TV',900,2024),
('EUROPE','WATCH',2000,2024),
('ASIA','MOBILE',1000,2024),
('NORTH AMERICA','MOBILE',1600,2023),
('EUROPE','TV',1500,2023),
('ASIA','TV',1100,2024),
('NORTH AMERICA','WATCH',1700,2024)
SELECT*FROM SALES_DATA
--PART-A--
-- Display Total Sales Amount by Region.
SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA GROUP BY REGION
--Display Average Sales Amount by Product
SELECT AVG(SALES_AMOUNT),PRODUCT FROM SALES_DATA GROUP BY PRODUCT
--Display Maximum Sales Amount by Year
SELECT  MAX(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR
--Display Minimum Sales Amount by Region and YearSELECT  MIN(SALES_AMOUNT),YEAR,REGION FROM SALES_DATA GROUP BY YEAR,REGION --Count of Products Sold by Region SELECT COUNT(PRODUCT),REGION FROM SALES_DATA GROUP BY REGION --Display Sales Amount by Year and Product SELECT  SUM(SALES_AMOUNT),YEAR,PRODUCT FROM SALES_DATA GROUP BY YEAR,PRODUCT --Display Regions with Total Sales Greater Than 5000 SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA GROUP BY REGION HAVING SUM(SALES_AMOUNT)>5000 --Display Products with Average Sales Less Than 10000 SELECT AVG(SALES_AMOUNT),PRODUCT FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000 --Display Years with Maximum Sales Exceeding 500 SELECT MAX(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR HAVING MAX(SALES_AMOUNT)>500 --Display Regions with at Least 3 Distinct Products Sold.  SELECT COUNT(PRODUCT),REGION FROM SALES_DATA GROUP BY REGION HAVING COUNT(PRODUCT) >=3  --Display Years with Minimum Sales Less Than 1000  SELECT MIN(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR HAVING MIN(SALES_AMOUNT)<1000  -- Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount  SELECT SUM(SALES_AMOUNT),REGION FROM SALES_DATA  WHERE YEAR  = 2023 GROUP BY REGION  --PART-B-- -- Display Count of Orders by Year and Region, Sorted by Year and Region  SELECT COUNT(SALES_AMOUNT),REGION,YEAR FROM SALES_DATA GROUP BY REGION , YEAR ORDER BY YEAR, REGION  --Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region  SELECT MAX(SALES_AMOUNT),REGION FROM SALES_DATA GROUP BY REGION HAVING  MAX(SALES_AMOUNT)>1000  ORDER BY  REGION  --Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending  SELECT SUM(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR HAVING  MAX(SALES_AMOUNT)<1000  ORDER BY  YEAR DESC ---Display Top 3 Regions by Total Sales Amount in Year 2024 SELECT TOP 3 REGION ,SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR = 2024  GROUP BY REGION  --PART-C-- --Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name SELECT AVG(SALES_AMOUNT),PRODUCT FROM SALES_DATA GROUP BY PRODUCT  HAVING  AVG(SALES_AMOUNT)>1000 AND AVG(SALES_AMOUNT)<2000  ORDER BY PRODUCT --Display Years with More Than 5 Orders from Each Region SELECT COUNT(SALES_AMOUNT),YEAR FROM SALES_DATA GROUP BY YEAR  HAVING  COUNT(SALES_AMOUNT)>5-- Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending SELECT AVG(SALES_AMOUNT),REGION FROM SALES_DATA WHERE YEAR = 2023 GROUP BY REGION HAVING  AVG(SALES_AMOUNT)>1500  ORDER BY AVG(SALES_AMOUNT) DESC-- Find out region wise duplicate productSELECT DISTINCT COUNT(PRODUCT),REGION FROM SALES_DATA GROUP BY REGION,PRODUCT HAVING COUNT(PRODUCT)>1

